version: "3.8"

services:
  traefik:
    container_name: traefik
    image: traefik:v3.0
    restart: always
    environment:
      DUCKDNS_TOKEN: "00000000-0000-0000-0000-000000000000"
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - traefik_config:/etc/traefik
      - traefik_certs:/letsencrypt
    networks:
      - local

volumes:
  traefik_config:
  traefik_certs:

networks:
  local:
    name: local
