version: "3.8"

services:
  guacamole:
    container_name: guacamole
    image: oznu/guacamole
    restart: always
    ports:
      - 8080:8080
    volumes:
      - config:/config
    networks:
      - local

volumes:
  config:

networks:
  local:
