version: "3.8"

services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: always
    privileged: true
    ports:
      - 8123:8123
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - config:/config
    networks:
      - local

volumes:
  config:

networks:
  local:
