version: "3.8"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole
    restart: always
    environment:
      - TZ=$TZ
      - WEBPASSWORD=$WEBPASSWORD
    volumes:
      - config:/etc/pihole
      - dnsmasq:/etc/dnsmasq.d
    ports:
      - 53:53
    networks:
      - local

volumes:
  config:
  dnsmasq:

networks:
  local:
