version: "3.8"

services:
  nginxproxymanager:
    container_name: nginxproxymanager
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - 80:80
      - 443:443
      - 81:81
    volumes:
      - nginxproxymanager_data:/data
      - nginxproxymanager_certs:/etc/letsencrypt
    networks:
      - local

volumes:
  nginxproxymanager_data:
  nginxproxymanager_certs:

networks:
  local:
    name: local
