version: "3.8"

services:
  traefik:
    container_name: traefik
    image: traefik:v2.10
    restart: always
    command: --api.insecure=true --providers.docker    
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml
      - traefik_config:/etc/traefik
      - traefik_certs:/ssl-certs

volumes:
  traefik_config:
  traefik_certs:

networks:
  local:
