version: "3.8"

services:
  traefik:
    container_name: traefik
    image: traefik:v3.0
    restart: always
    environment:
      - DUCKDNS_TOKEN=$DUCKDNS_TOKEN
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - config:/etc/traefik
      - certs:/letsencrypt
    networks:
      - local

volumes:
  config:
  certs:

networks:
  local:
