version: "3.8"

services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=$GF_SECURITY_ADMIN_USER
      - GF_SECURITY_ADMIN_PASSWORD=$GF_SECURITY_ADMIN_PASSWORD
      - GF_INSTALL_PLUGINS=
    volumes:
      - data:/var/lib/grafana
    networks:
      - local

volumes:
  data:

networks:
  local:
