version: "3.8"

services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - local

volumes:
  grafana_data:

networks:
  local:
    name: local
    external: true
