version: "3.8"

services:
  dashy:
    container_name: dashy
    image: lissy93/dashy
    restart: always
    volumes:
      - dashy_config:/app/public
    networks:
      - local

volumes:
  dashy_config:

networks:
  local:
    name: local
    external: true
