version: "3.8"

services:
  dashy:
    container_name: dashy
    image: lissy93/dashy
    restart: always
    environment:
      - NODE_ENV=production
      - UID=1000
      - GID=100
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - 80:80
    volumes:
      - ./dashy.yml:/app/public/conf.yml
      - dashy_config:/app/public
    networks:
      - local

volumes:
  dashy_config:

networks:
  local:
