version: "3.8"

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - data:/var/lib/mysql
    networks:
      - local

volumes:
  data:

networks:
  local:
