version: "3.8"

services:
  openvpn:
    container_name: openvpn
    image: kylemanna/openvpn
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - 1194:1194/udp
    volumes:
      - config:/etc/openvpn
    networks:
      - local

volumes:
  config:

networks:
  local:
