version: "3.8"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    labels:
      traefik.enable: "true"
      traefik.http.routers.portainer.entrypoints: "web, websecure"
      traefik.http.routers.portainer.rule: "Host(`kde.portainer.com`)"
      traefik.http.routers.portainer.tls: "true"
      traefik.http.routers.portainer.tls.certresolver: "production"
    networks:
      - local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:

networks:
  local:
