version: "3.8"

services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: always
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - homeassistant_config:/config
    networks:
      - local

volumes:
  homeassistant_config:

networks:
  local:
    name: local
    external: true
