version: "3.8"

services:
  influxdb:
    container_name: influxdb
    image: influxdb:1.8-alpine
    restart: always
    environment:
      - INFLUXDB_DB=$INFLUXDB_DB
      - INFLUXDB_ADMIN_USER=$INFLUXDB_ADMIN_USER
      - INFLUXDB_ADMIN_PASSWORD=$INFLUXDB_ADMIN_PASSWORD
    volumes:
      - data:/var/lib/influxdb
    networks:
      - local

volumes:
  data:

networks:
  local:
